version: "3.9"
services:
  mongoDB:
    image: mongo:focal
    ports:
      - "27018:27017"
    container_name: mongoDB
    volumes:
      - mongoDB:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: practice-mq
    env_file:
      - ./.env
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      noting-app-network:
  auth:
    build:
      context: apps/auth
      dockerfile: Dockerfile
      target: development
    ports:
      - "8002:8002"
    volumes:
      - ./apps/auth:/app/
      - ./apps/auth/node_modules:/app/node_modules
    environment:
      - DATABASE_URL=mongodb://mongoDB:27018
      - PORT=8002
    depends_on:
      - mailer
    networks:
      noting-app-network:
  note:
    build:
      context: apps/note
      dockerfile: Dockerfile
      target: development
    ports:
      - "8001:8001"
    volumes:
      - ./apps/note:/app/
      - ./apps/note/node_modules:/app/node_modules
    environment:
      - DATABASE_URL=mongodb://mongoDB:27018
      - PORT=8001
    depends_on:
      - auth
    networks:
      noting-app-network:
  user:
    build:
      context: apps/user
      dockerfile: Dockerfile
      target: development
    ports:
      - "8003:8003"
    volumes:
      - ./apps/user:/app/
      - ./apps/user/node_modules:/app/node_modules
    depends_on:
      - auth
    environment:
      - DATABASE_URL=mongodb://mongoDB:27018
      - PORT=8003
    networks:
      noting-app-network:
  mailer:
    build:
      context: apps/email
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./apps/email:/app/
      - ./apps/email/node_modules:/app/node_modules
    networks:
      noting-app-network:
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./packages/proxy
    depends_on:
      - auth
      - note
      - user
    ports:
      - "8005:80"
volumes:
  mongoDB:
  rabbitmq_data:
networks:
  noting-app-network:
    driver: bridge