version: "3.8"
services:
  mongodb:
    image: mongo:focal
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongodb:/data/db
    networks:
      noting-app-network:
  auth:
    build:
      context: apps/auth
      dockerfile: Dockerfile
      target: development
    ports:
      - "8002:8002"
    volumes:
      - ./apps/auth:/app/
      - ./apps/auth/node_modules:/app/node_modules
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb/noting-app
      PORT: 8002
    networks:
      noting-app-network:
  note:
    build:
      context: apps/note
      dockerfile: Dockerfile
      target: development
    ports:
      - "8001:8001"
    volumes:
      - ./apps/note:/app/
      - ./apps/note/node_modules:/app/node_modules
    environment:
      DATABASE_URL: mongodb://mongodb/noting-app
      PORT: 8001
    depends_on:
      - auth
    networks:
      noting-app-network:
  user:
    build:
      context: apps/user
      dockerfile: Dockerfile
      target: development
    ports:
      - "8003:8003"
    volumes:
      - ./apps/user:/app/
      - ./apps/user/node_modules:/app/node_modules
    depends_on:
      - auth
    environment:
      DATABASE_URL: mongodb://mongodb/noting-app
      PORT: 8003
    networks:
      noting-app-network:
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./packages/proxy
    depends_on:
      - auth
      - note
      - user
    ports:
      - "8005:80"
    networks:
      noting-app-network:
volumes:
  mongodb:
networks:
  noting-app-network:
    driver: bridge